title: 1riz
description: personal projects
show_downloads: false
google_analytics:
github:
  repository_url: https://github.com/1riz
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
